-- VetHome Pro v10 - workspace multiusuario
-- Ejecutar en Supabase SQL Editor.
-- Permite que varios usuarios de Auth compartan los mismos datos operativos.
-- Seguro para datos existentes: crea workspace/membresias y policies sin borrar registros.

create extension if not exists pgcrypto;

create table if not exists public.app_workspaces (
    id uuid primary key default gen_random_uuid(),
    nombre text not null default 'VetHome',
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table if not exists public.app_workspace_members (
    id bigint generated by default as identity primary key,
    workspace_id uuid references public.app_workspaces(id) on delete cascade not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    role text not null default 'member',
    created_at timestamp with time zone not null default now(),
    unique (workspace_id, user_id)
);

create table if not exists public.app_state (
    user_id uuid references auth.users(id) on delete cascade primary key,
    data jsonb not null default '{}'::jsonb,
    updated_at timestamp with time zone not null default now()
);

create or replace function public.is_workspace_member(target_workspace uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select exists (
        select 1
        from public.app_workspace_members member
        where member.workspace_id = target_workspace
          and member.user_id = auth.uid()
    );
$$;

create or replace function public.ensure_personal_workspace()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
    workspace uuid;
begin
    select member.workspace_id
      into workspace
      from public.app_workspace_members member
     where member.user_id = auth.uid()
     order by member.created_at
     limit 1;

    if workspace is not null then
        return workspace;
    end if;

    insert into public.app_workspaces (nombre, created_by)
    values ('VetHome', auth.uid())
    returning id into workspace;

    insert into public.app_workspace_members (workspace_id, user_id, role)
    values (workspace, auth.uid(), 'owner');

    return workspace;
end;
$$;

alter table public.app_workspaces enable row level security;
alter table public.app_workspace_members enable row level security;

drop policy if exists "Workspaces visibles por miembros" on public.app_workspaces;
create policy "Workspaces visibles por miembros" on public.app_workspaces
    for select using (public.is_workspace_member(id));

drop policy if exists "Crear workspace propio" on public.app_workspaces;
create policy "Crear workspace propio" on public.app_workspaces
    for insert with check (created_by = auth.uid());

drop policy if exists "Actualizar workspace por miembros" on public.app_workspaces;
create policy "Actualizar workspace por miembros" on public.app_workspaces
    for update using (public.is_workspace_member(id))
    with check (public.is_workspace_member(id));

drop policy if exists "Membresias visibles por miembros" on public.app_workspace_members;
create policy "Membresias visibles por miembros" on public.app_workspace_members
    for select using (public.is_workspace_member(workspace_id) or user_id = auth.uid());

drop policy if exists "Crear membresia propia" on public.app_workspace_members;
create policy "Crear membresia propia" on public.app_workspace_members
    for insert with check (user_id = auth.uid() or public.is_workspace_member(workspace_id));

do $$
declare
    tabla text;
begin
    foreach tabla in array array[
        'clientes',
        'mascotas',
        'servicios',
        'inventario',
        'agenda',
        'consultas',
        'pagos',
        'servicios_externos',
        'gastos',
        'movimientos_inventario',
        'app_state'
    ]
    loop
        execute format('alter table if exists public.%I add column if not exists workspace_id uuid references public.app_workspaces(id) on delete cascade', tabla);
    end loop;
end $$;

insert into public.app_workspaces (id, nombre, created_by)
select distinct user_id, 'VetHome', user_id
from (
    select user_id from public.clientes
    union select user_id from public.mascotas
    union select user_id from public.servicios
    union select user_id from public.inventario
    union select user_id from public.agenda
    union select user_id from public.consultas
    union select user_id from public.pagos
    union select user_id from public.servicios_externos
    union select user_id from public.gastos
    union select user_id from public.movimientos_inventario
) usuarios
where user_id is not null
on conflict (id) do nothing;

insert into public.app_workspace_members (workspace_id, user_id, role)
select id, created_by, 'owner'
from public.app_workspaces
where created_by is not null
on conflict (workspace_id, user_id) do nothing;

update public.clientes set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.mascotas set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.servicios set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.inventario set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.agenda set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.consultas set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.pagos set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.servicios_externos set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.gastos set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.movimientos_inventario set workspace_id = user_id where workspace_id is null and user_id is not null;
update public.app_state set workspace_id = user_id where workspace_id is null and user_id is not null;

create index if not exists idx_clientes_workspace on public.clientes(workspace_id);
create index if not exists idx_mascotas_workspace on public.mascotas(workspace_id);
create index if not exists idx_servicios_workspace on public.servicios(workspace_id);
create index if not exists idx_inventario_workspace on public.inventario(workspace_id);
create index if not exists idx_agenda_workspace_fecha on public.agenda(workspace_id, fecha);
create index if not exists idx_consultas_workspace_fecha on public.consultas(workspace_id, fecha_iso desc);
create index if not exists idx_pagos_workspace_fecha on public.pagos(workspace_id, fecha_iso desc);
create index if not exists idx_servicios_externos_workspace_fecha on public.servicios_externos(workspace_id, fecha_iso desc);
create index if not exists idx_gastos_workspace_fecha on public.gastos(workspace_id, fecha_iso desc);
create index if not exists idx_movimientos_workspace_fecha on public.movimientos_inventario(workspace_id, fecha_iso desc);
create index if not exists idx_app_state_workspace on public.app_state(workspace_id);

create unique index if not exists uq_clientes_workspace_legacy on public.clientes(workspace_id, legacy_id);
create unique index if not exists uq_mascotas_workspace_legacy on public.mascotas(workspace_id, legacy_id);
create unique index if not exists uq_servicios_workspace_legacy on public.servicios(workspace_id, legacy_id);
create unique index if not exists uq_inventario_workspace_legacy on public.inventario(workspace_id, legacy_id);
create unique index if not exists uq_agenda_workspace_legacy on public.agenda(workspace_id, legacy_id);
create unique index if not exists uq_consultas_workspace_legacy on public.consultas(workspace_id, legacy_id);
create unique index if not exists uq_pagos_workspace_legacy on public.pagos(workspace_id, legacy_id);
create unique index if not exists uq_servicios_externos_workspace_legacy on public.servicios_externos(workspace_id, legacy_id);
create unique index if not exists uq_gastos_workspace_legacy on public.gastos(workspace_id, legacy_id);
create unique index if not exists uq_movimientos_workspace_legacy on public.movimientos_inventario(workspace_id, legacy_id);
create unique index if not exists uq_app_state_workspace on public.app_state(workspace_id);

drop policy if exists "Clientes del usuario" on public.clientes;
create policy "Clientes del usuario" on public.clientes
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Mascotas del usuario" on public.mascotas;
create policy "Mascotas del usuario" on public.mascotas
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Servicios del usuario" on public.servicios;
create policy "Servicios del usuario" on public.servicios
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Inventario del usuario" on public.inventario;
create policy "Inventario del usuario" on public.inventario
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Agenda del usuario" on public.agenda;
create policy "Agenda del usuario" on public.agenda
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Consultas del usuario" on public.consultas;
create policy "Consultas del usuario" on public.consultas
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Pagos del usuario" on public.pagos;
create policy "Pagos del usuario" on public.pagos
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Servicios externos del usuario" on public.servicios_externos;
create policy "Servicios externos del usuario" on public.servicios_externos
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Gastos del usuario" on public.gastos;
create policy "Gastos del usuario" on public.gastos
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

drop policy if exists "Movimientos de inventario del usuario" on public.movimientos_inventario;
create policy "Movimientos de inventario del usuario" on public.movimientos_inventario
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

alter table public.app_state enable row level security;

drop policy if exists "App state del workspace" on public.app_state;
create policy "App state del workspace" on public.app_state
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));
