-- VetHome Pro v10 - vacunas como tabla real
-- Mantiene el JSON existente, pero crea una tabla normalizada para escalar.
-- Sirve para consultar refuerzos anuales sin depender solo del historial embebido en mascotas.

create table if not exists public.vacunas_paciente (
    id bigint generated by default as identity primary key,
    workspace_id uuid references public.app_workspaces(id) on delete cascade,
    user_id uuid references auth.users(id) on delete cascade not null,
    legacy_id bigint,
    cliente_id bigint references public.clientes(id) on delete set null,
    mascota_id bigint references public.mascotas(id) on delete cascade,
    consulta_id bigint references public.consultas(id) on delete set null,
    nombre text not null,
    fecha_aplicacion date,
    fecha_refuerzo date,
    lote text,
    laboratorio text,
    desparasitante text,
    nota text,
    origen text not null default 'Manual',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index if not exists idx_vacunas_workspace_refuerzo on public.vacunas_paciente(workspace_id, fecha_refuerzo);
create index if not exists idx_vacunas_mascota_fecha on public.vacunas_paciente(mascota_id, fecha_aplicacion desc);
create unique index if not exists uq_vacunas_workspace_legacy on public.vacunas_paciente(workspace_id, legacy_id);

alter table public.vacunas_paciente enable row level security;

drop policy if exists "Vacunas del workspace" on public.vacunas_paciente;
create policy "Vacunas del workspace" on public.vacunas_paciente
    for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
    with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'vacunas_paciente'
    ) then
        alter publication supabase_realtime add table public.vacunas_paciente;
    end if;
end $$;
