-- VetHome Pro v10 - auditoria, indices y validaciones base

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    workspace_id uuid references public.app_workspaces(id) on delete cascade,
    user_id uuid references auth.users(id) on delete set null,
    tabla text not null,
    accion text not null,
    registro_id text,
    resumen text,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_audit_workspace_fecha on public.audit_logs(workspace_id, created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists "Auditoria visible por workspace" on public.audit_logs;
create policy "Auditoria visible por workspace" on public.audit_logs
    for select using (public.is_workspace_member(workspace_id));

drop policy if exists "Auditoria insertable por workspace" on public.audit_logs;
create policy "Auditoria insertable por workspace" on public.audit_logs
    for insert with check (auth.uid() = user_id and public.is_workspace_member(workspace_id));

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'pagos_total_no_negativo') then
        alter table public.pagos add constraint pagos_total_no_negativo check (total >= 0);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'servicios_externos_total_no_negativo') then
        alter table public.servicios_externos add constraint servicios_externos_total_no_negativo check (total >= 0);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'gastos_monto_no_negativo') then
        alter table public.gastos add constraint gastos_monto_no_negativo check (monto >= 0);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'inventario_stock_no_negativo') then
        alter table public.inventario add constraint inventario_stock_no_negativo check (stock >= 0);
    end if;
end $$;
