-- VetHome Pro v10 Schnauzer
-- Catalogo de clinicas externas para servicios referidos.
-- Seguro para datos existentes: solo crea tabla/columnas si no existen.

create table if not exists public.clinicas_externas (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    workspace_id uuid,
    legacy_id bigint,
    nombre text not null,
    contacto text,
    telefono text,
    direccion text,
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone default now()
);

alter table public.clinicas_externas
    add column if not exists workspace_id uuid;

alter table public.servicios_externos
    add column if not exists clinica_legacy_id bigint;

create unique index if not exists uq_clinicas_externas_workspace_legacy
    on public.clinicas_externas(workspace_id, legacy_id);

create unique index if not exists uq_clinicas_externas_user_legacy
    on public.clinicas_externas(user_id, legacy_id);

create index if not exists idx_clinicas_externas_scope_nombre
    on public.clinicas_externas(workspace_id, user_id, nombre);

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'servicios_externos'
          and column_name = 'workspace_id'
    ) then
        create index if not exists idx_servicios_externos_clinica_legacy
            on public.servicios_externos(workspace_id, user_id, clinica_legacy_id);
    else
        create index if not exists idx_servicios_externos_clinica_legacy
            on public.servicios_externos(user_id, clinica_legacy_id);
    end if;
end $$;

alter table public.clinicas_externas enable row level security;

drop policy if exists "Clinicas externas del usuario" on public.clinicas_externas;

do $$
begin
    if to_regprocedure('public.is_workspace_member(uuid)') is not null then
        execute $policy$
            create policy "Clinicas externas del usuario" on public.clinicas_externas
                for all using (auth.uid() = user_id or public.is_workspace_member(workspace_id))
                with check (auth.uid() = user_id and (workspace_id is null or public.is_workspace_member(workspace_id)))
        $policy$;
    else
        execute $policy$
            create policy "Clinicas externas del usuario" on public.clinicas_externas
                for all using (auth.uid() = user_id)
                with check (auth.uid() = user_id)
        $policy$;
    end if;
end $$;

do $$
begin
    alter table public.clinicas_externas replica identity full;

    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'clinicas_externas'
    ) then
        alter publication supabase_realtime add table public.clinicas_externas;
    end if;
exception
    when undefined_object then
        null;
end $$;
