-- VetHome Pro - esquema normalizado para Supabase
-- Ejecutar en Supabase SQL Editor con un usuario dueño del proyecto.
-- Mantiene tus tablas existentes cuando ya existen y agrega lo necesario.

create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'vet-files',
    'vet-files',
    true,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    created_at timestamp without time zone default now()
);

alter table public.clientes
    add column if not exists user_id uuid references auth.users(id) on delete cascade,
    add column if not exists nombre text,
    add column if not exists telefono text,
    add column if not exists email text,
    add column if not exists direccion text,
    add column if not exists notas text,
    add column if not exists id_photo text,
    add column if not exists legacy_id bigint,
    add column if not exists updated_at timestamp without time zone default now();

create table if not exists public.mascotas (
    id bigint generated by default as identity primary key,
    created_at timestamp without time zone default now()
);

alter table public.mascotas
    add column if not exists user_id uuid references auth.users(id) on delete cascade,
    add column if not exists cliente_id bigint references public.clientes(id) on delete cascade,
    add column if not exists nombre text,
    add column if not exists especie text,
    add column if not exists raza text,
    add column if not exists edad integer,
    add column if not exists peso numeric,
    add column if not exists esterilizado text,
    add column if not exists foto text,
    add column if not exists estudios jsonb not null default '[]'::jsonb,
    add column if not exists legacy_id bigint,
    add column if not exists updated_at timestamp without time zone default now();

create table if not exists public.servicios (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    nombre text not null,
    precio numeric not null default 0,
    activo boolean not null default true,
    legacy_id bigint,
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone default now()
);

create table if not exists public.inventario (
    id bigint generated by default as identity primary key,
    created_at timestamp without time zone default now()
);

alter table public.inventario
    add column if not exists user_id uuid references auth.users(id) on delete cascade,
    add column if not exists nombre text,
    add column if not exists stock integer default 0,
    add column if not exists unidad text,
    add column if not exists categoria text default 'Medicamento',
    add column if not exists stock_minimo integer default 3,
    add column if not exists lote text,
    add column if not exists caducidad date,
    add column if not exists proveedor text,
    add column if not exists legacy_id bigint,
    add column if not exists updated_at timestamp without time zone default now();

create table if not exists public.agenda (
    id bigint generated by default as identity primary key
);

alter table public.agenda
    add column if not exists user_id uuid references auth.users(id) on delete cascade,
    add column if not exists cliente_id bigint references public.clientes(id) on delete set null,
    add column if not exists mascota_id bigint references public.mascotas(id) on delete set null,
    add column if not exists fecha date,
    add column if not exists hora time without time zone,
    add column if not exists direccion text,
    add column if not exists notas text,
    add column if not exists estado text default 'Programada',
    add column if not exists legacy_id bigint,
    add column if not exists created_at timestamp without time zone default now(),
    add column if not exists updated_at timestamp without time zone default now();

create table if not exists public.consultas (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    cliente_id bigint references public.clientes(id) on delete set null,
    mascota_id bigint references public.mascotas(id) on delete cascade,
    cita_id bigint references public.agenda(id) on delete set null,
    fecha_iso timestamp with time zone not null default now(),
    fecha_texto text,
    tipo text,
    peso text,
    temperatura text,
    motivo text,
    tratamiento text,
    sintomas text,
    vacunas text,
    desparasitante text,
    disclaimer text,
    notas_rapidas text,
    insumos jsonb not null default '[]'::jsonb,
    vacunas_control_stock jsonb,
    firma_dueno text,
    firma_vet text,
    legacy_id bigint,
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone default now()
);

alter table public.consultas
    add column if not exists notas_rapidas text;

create table if not exists public.pagos (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    consulta_id bigint references public.consultas(id) on delete cascade,
    cliente_id bigint references public.clientes(id) on delete set null,
    mascota_id bigint references public.mascotas(id) on delete set null,
    servicio_cobrado text,
    total numeric not null default 0,
    metodo_pago text default 'Efectivo',
    estado_pago text default 'Pagado',
    nota_pago text,
    fecha_iso timestamp with time zone not null default now(),
    legacy_id bigint,
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone default now()
);

create table if not exists public.servicios_externos (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    legacy_id bigint,
    fecha_iso timestamp with time zone not null default now(),
    fecha_texto text,
    cliente_nombre text,
    servicio text,
    total numeric not null default 0,
    metodo_pago text default 'Efectivo',
    estado_pago text default 'Pagado',
    nota text,
    tipo text default 'Servicio externo',
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone default now()
);

create table if not exists public.movimientos_inventario (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    inventario_id bigint references public.inventario(id) on delete set null,
    item_nombre text,
    tipo text,
    cantidad integer not null default 0,
    stock_resultante integer not null default 0,
    motivo text,
    fecha_iso timestamp with time zone not null default now(),
    legacy_id bigint,
    created_at timestamp without time zone default now()
);

create index if not exists idx_clientes_user_id on public.clientes(user_id);
create index if not exists idx_mascotas_cliente_id on public.mascotas(cliente_id);
create index if not exists idx_mascotas_user_id on public.mascotas(user_id);
create index if not exists idx_agenda_user_fecha on public.agenda(user_id, fecha);
create index if not exists idx_consultas_mascota_fecha on public.consultas(mascota_id, fecha_iso desc);
create index if not exists idx_pagos_user_fecha on public.pagos(user_id, fecha_iso desc);
create index if not exists idx_servicios_externos_user_fecha on public.servicios_externos(user_id, fecha_iso desc);
create index if not exists idx_inventario_user_id on public.inventario(user_id);
create index if not exists idx_movimientos_user_fecha on public.movimientos_inventario(user_id, fecha_iso desc);

create unique index if not exists uq_clientes_user_legacy on public.clientes(user_id, legacy_id);
create unique index if not exists uq_mascotas_user_legacy on public.mascotas(user_id, legacy_id);
create unique index if not exists uq_servicios_user_legacy on public.servicios(user_id, legacy_id);
create unique index if not exists uq_inventario_user_legacy on public.inventario(user_id, legacy_id);
create unique index if not exists uq_agenda_user_legacy on public.agenda(user_id, legacy_id);
create unique index if not exists uq_consultas_user_legacy on public.consultas(user_id, legacy_id);
create unique index if not exists uq_pagos_user_legacy on public.pagos(user_id, legacy_id);
create unique index if not exists uq_servicios_externos_user_legacy on public.servicios_externos(user_id, legacy_id);
create unique index if not exists uq_movimientos_user_legacy on public.movimientos_inventario(user_id, legacy_id);

alter table public.clientes enable row level security;
alter table public.mascotas enable row level security;
alter table public.servicios enable row level security;
alter table public.inventario enable row level security;
alter table public.agenda enable row level security;
alter table public.consultas enable row level security;
alter table public.pagos enable row level security;
alter table public.servicios_externos enable row level security;
alter table public.movimientos_inventario enable row level security;

drop policy if exists "Allow select" on public.clientes;
drop policy if exists "Allow insert" on public.clientes;

drop policy if exists "Clientes del usuario" on public.clientes;
create policy "Clientes del usuario" on public.clientes
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Mascotas del usuario" on public.mascotas;
create policy "Mascotas del usuario" on public.mascotas
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Servicios del usuario" on public.servicios;
create policy "Servicios del usuario" on public.servicios
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Inventario del usuario" on public.inventario;
create policy "Inventario del usuario" on public.inventario
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Agenda del usuario" on public.agenda;
create policy "Agenda del usuario" on public.agenda
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Consultas del usuario" on public.consultas;
create policy "Consultas del usuario" on public.consultas
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Pagos del usuario" on public.pagos;
create policy "Pagos del usuario" on public.pagos
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Servicios externos del usuario" on public.servicios_externos;
create policy "Servicios externos del usuario" on public.servicios_externos
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Movimientos de inventario del usuario" on public.movimientos_inventario;
create policy "Movimientos de inventario del usuario" on public.movimientos_inventario
    for all using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "Archivos veterinaria lectura publica" on storage.objects;
create policy "Archivos veterinaria lectura publica" on storage.objects
    for select using (bucket_id = 'vet-files');

drop policy if exists "Archivos veterinaria insertar usuario" on storage.objects;
create policy "Archivos veterinaria insertar usuario" on storage.objects
    for insert with check (
        bucket_id = 'vet-files'
        and auth.uid()::text = (storage.foldername(name))[1]
    );

drop policy if exists "Archivos veterinaria actualizar usuario" on storage.objects;
create policy "Archivos veterinaria actualizar usuario" on storage.objects
    for update using (
        bucket_id = 'vet-files'
        and auth.uid()::text = (storage.foldername(name))[1]
    )
    with check (
        bucket_id = 'vet-files'
        and auth.uid()::text = (storage.foldername(name))[1]
    );

drop policy if exists "Archivos veterinaria borrar usuario" on storage.objects;
create policy "Archivos veterinaria borrar usuario" on storage.objects
    for delete using (
        bucket_id = 'vet-files'
        and auth.uid()::text = (storage.foldername(name))[1]
    );

do $$
declare
    tabla text;
begin
    foreach tabla in array array[
        'clientes',
        'mascotas',
        'servicios',
        'inventario',
        'agenda',
        'consultas',
        'pagos',
        'servicios_externos',
        'movimientos_inventario'
    ]
    loop
        if not exists (
            select 1
            from pg_publication_tables
            where pubname = 'supabase_realtime'
              and schemaname = 'public'
              and tablename = tabla
        ) then
            execute format('alter publication supabase_realtime add table public.%I', tabla);
        end if;
    end loop;
end $$;
